### ISSUE TITLE
Provide Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type properties

### ISSUE THREAD

**Issue by deepakjois** [grigorig/ucdn#10]
I am writing Lua bindings for ucdn at https://github.com/deepakjois/luaucdn, with the ultimate goal of implementing a pure Lua version of the [Unicode Bidirectional Algorithm](http://unicode.org/reports/tr9/).

One part of algorithm utilizes the properties Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type defined in the [BidiBrackets.txt file](http://www.unicode.org/Public/UCD/latest/ucd/BidiBrackets.txt). Both of these are derived properties, so I suppose it is possible to obtain them by using the current data and API methods made available by ucdn.

However, there is also this warning in [UAX #44](http://www.unicode.org/reports/tr44/#Simple_Derived):

> Implementations should simply use the derived properties, and should not try to rederive them from lists of simple properties and collections of rules, because of the chances for error and divergence when doing so.

In light of that, what is your opinion on providing Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type directly in ucdn?

**Comment by grigorig** [comment]
These properties have very specific uses. I think it might be more useful to bundle a property database with everything required for the Unicode Bidirectional Algorithm into the library that implements this algorithm.

**Comment by grigorig** [comment]
Note: maybe it would be worthwhile to make a spinoff C library that implements the Unicode BiDi algorithm. I have some interest in a permissively licensed library for the Unicode Bidirectional Algorithm. FriBiDi isn't that great.

**Comment by deepakjois** [comment]
I am definitely not the right person to write an implementation of the Unicode BiDi algorithm in C. Whatever C I have written so far is not out of choice, but due to lack of any other alternatives.

I am using ucdn was because I cannot find a decent Unicode support library in Lua, and ucdn has a simple clean C API, that can be easily wrapped with Lua’s C API support.

My real objective is to write some Lua code to extend the LuaTeX typesetting system with better BiDi and non-Latin script capabilities. A while ago, I wrote [Lua bindings for Harfbuzz](https://github.com/deepakjois/luaharfbuzz). Then I realised, I also need BiDi and script itemization, which led me to ucdn. I would prefer writing a BiDi implementation in Lua than trying to wrap FriBidi (wrapping it seems a bit too tedious, and it’s a bit complex as well).

If you think Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type are too specific, I will incorporate it inside of my own BiDi library, and continue to use ucdn for the other stuff. So feel free to close the issue.

I am just curious however:
* What is the criteria for including/excluding properties in ucdn?
* What projects use ucdn (I only know of Harfbuzz)?

**Comment by grigorig** [comment]
Well, UCDN was designed as a Unicode support library for HarfBuzz. There are some other projects that use it, for instance MuPDF.

There aren't any hard criterions about what can or should be included in UCDN, but I'd like to avoid properties that have only very specific use in some special cases. Although I already had the idea that it may be nice to modularize the library so that you can decide at compile time what should be included.

**Comment by deepakjois** [comment]
> OTOH, it looks like the BiDi bracket properties are very limited in number, so it should have low overhead to include these features. If it boils down to a single digit number of KB of additional binary size, I'll likely merge a PR to add this.

I can try to create a PR. From what I can see, I need start by adding an entry for BidiBrackets.txt to makeunicodedata.py. Then I need to parse the data in the file. Things are a bit confusing after that. Do you have any suggestions to proceed or some part of the code to look at, which I can replicate.

**Comment by deepakjois** [comment]
Please see #11

**Comment by grigorig** [comment]
Done.

**Comment by deepakjois** [comment]
Thank you.
