### ISSUE TITLE
Update to Unicode 10.0

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [grigorig/ucdn#16]

**Comment by grigorig** [comment]
I didn't notice that Unicode 10.0 was released. Working on it!

**Comment by grigorig** [comment]
Unicode 10.0 updates and several unit tests have been added.

**Comment by KrasnayaPloshchad** [comment]
OK, does it support vertical orientation property?

**Comment by grigorig** [comment]
UCDN currently does not provide that property. Please open a separate issue. Feel free to open a pull request as well.

**Comment by KrasnayaPloshchad** [comment]
Yes, I will report. 🤝
