### ISSUE TITLE
Standard decompositions are NOT always pairwise

### ISSUE THREAD

**Issue by behdad** [grigorig/ucdn#18]
Please revert 06132612ba5cc4ae8209eefd969e9e0288d49295.  That is not true, and it breaks decomposition for U+212B ANGSTROM SIGN and possibly a few other characters.  We've reverted that in HarfBuzz.  Caught by HB's test-unicode.c

**Comment by grigorig** [comment]
Looks like I have some more work to do to improve UCDN's own tests. Thanks for thead heads-up!
