### ISSUE TITLE
Mistake in pregenerated database.

### ISSUE THREAD

**Issue by crlf0710** [grigorig/ucdn#6]
Hi, i think there's a problem with the ````makeunicodedata.py```` script. The ````general_category```` column of the code points in a range (such as U+5000 in U+4E00..9FCC range) is incorrectly set to 
UCDN_GENERAL_CATEGORY_CN, which means it is not assigned. However it should be same with the 'First>' and 'Last>' code point, which is meaningful.

Look forward for someone getting this fixed. Thanks a lot.

**Comment by grigorig** [comment]
Nice find.

**Comment by behdad** [comment]
Gregori, can you send a PR to HarfBuzz for this fix?

Also, do you have Unicode 8 updates coming up soon?

**Comment by grigorig** [comment]
@behdad, I already added Unicode 8.0 support. Sure, I can update Harfbuzz.

**Comment by behdad** [comment]
@grigorig That would be great.  Thanks!

**Comment by grigorig** [comment]
@behdad I already made a pull request.

**Comment by crlf0710** [comment]
Hi, i guess you should update the pre-generated database too :)

**Comment by grigorig** [comment]
I already did that.
